version: '3'

services:
  api:
    build: ./src/ProductManagement.API
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=productmanagement;Username=postgres;Password=postgres

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=productmanagement
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: