name: Review Changes with Model

on:
  pull_request_target:
    branches:
      - main  # Adjust this to your default branch, e.g., 'master' or 'develop'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Allows the workflow to write comments on issues and pull requests
    env:
      MODEL_NAME: "deepseek-r1:latest"  # Specify the model you want to use
    steps:
      # Checkout the base branch to ensure no untrusted code from the PR is executed
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      # Fetch the pull request branch to compare changes
      - name: Fetch pull request branch
        run: git fetch origin pull/${{ github.event.pull_request.number }}/head:pr-branch

      # Generate a diff between the base branch and the pull request
      - name: Generate diff
        run: git diff ${{ github.event.pull_request.base.sha }} pr-branch > changeset.diff

      # Install Ollama, a tool to run the model
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh
          ollama --version  # Confirm the installation

      # Pull the specified model if it’s not already cached
      - name: Pull Model if not cached
        run: ollama pull ${{ env.MODEL_NAME }}

      # Start the Ollama server in the background
      - name: Start Ollama Server
        run: |
          ollama serve &
          timeout 30s bash -c "until curl -s http://localhost:11434 > /dev/null; do sleep 1; done"

      # Send the diff to the model for review and capture the response
      - name: Review Changes with Model
        run: |
          REVIEW=$(curl -s -X POST http://localhost:11434/api/generate \
            -d '{
              "model": "'$MODEL_NAME'",
              "prompt": "Review the following code changes and provide feedback:\n\n$(cat changeset.diff)",
              "stream": false
            }' | jq -r '.response')
          echo "Review: $REVIEW"
          echo "REVIEW=$REVIEW" >> $GITHUB_ENV

      # Post the model’s review as a comment on the pull request
      - name: Post Review Comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const review = process.env.REVIEW;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `### Model Review\n\n${review}`
            });